version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "32773:27017"
    volumes:
      - /data/configdb
      - /data/db
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.16
      - JSYAML_VERSION=3.13.1
      - MONGO_PACKAGE=mongodb-org
      - MONGO_REPO=repo.mongodb.org
      - MONGO_MAJOR=7.0
      - MONGO_VERSION=7.0.2
      - HOME=/data/db
    labels:
      - 'org.opencontainers.image.ref.name=ubuntu'
      - 'org.opencontainers.image.version=22.04'