# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory in the Docker container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Use Docker build secrets for npm authentication
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm install

# Copy the application code to the working directory
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]